# Generated by Django 2.0.1 on 2018-04-06 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('city', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(10)])),
                ('email', models.EmailField(max_length=254)),
                ('facebook_link', models.URLField()),
                ('linkedin_link', models.URLField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
