# Generated by Django 2.0.1 on 2018-10-11 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20180814_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('job_image', models.ImageField(upload_to='uploaded_images')),
                ('description', models.CharField(max_length=200, null=True)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Info')),
            ],
        ),
    ]
