# Generated by Django 2.0.1 on 2018-10-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20181011_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
