# Generated by Django 2.0.1 on 2018-10-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_job_job_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_end',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
